[server]
# port = 7777
runOnSave = true

[theme]
base="dark"
# primaryColor="#F63366"                # default FF4B4B
# backgroundColor="#FFFFFF"             # default 0E1117
# secondaryBackgroundColor="#F0F2F6"    # default 262730
# textColor="#262730"                   # default FAFAFA
# font="sans serif"

# [client]
# toolbarMode = "minimal"